name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
    
    - name: upload binary artifact
      uses: actions/upload-artifact@v2
      with:
        name: go_bot
        path: ./go_bot
        
    - name: scp-deployer
      uses: siva1024/scp-deployer@v1.0
      with:
        # ssh remote host
        host: ${{ secrets.HOST }}
        # ssh remote user
        username: ${{ secrets.USERNAME }}
        # ssh remote port
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: ${{ secrets.REMOTE_KEY }}
        # source to copy from
        source: "./go_bot"
        # destination to download on server
        target: "~/"
